# Multple Linear Regression 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


## Importing de Dataset

In [4]:
# Importamos y mostramos las primeras filas de nuestro objeto para ver que se ha cargado correctamente.
df = pd.read_csv('C:/Users/Juan Carlos/Documents/MachineLearning/Datasets/New_Position.csv')
df.head()

Position  Level  Years  Languages  Salary
0   Business Analyst      1      1          2   45000
1  Junior Consultant      2      1          1   50000
2  Senior Consultant      3      1          2   60000
3            Manager      4      1          1   80000
4    Country Manager      5      1          4  110000

In [25]:
#Definimos nuestras variables
X = df.iloc[:, 0:4].values
y = df.iloc[:,-1]

In [26]:
print(X)

[['Business Analyst' 1 1 2]
 ['Junior Consultant' 2 1 1]
 ['Senior Consultant' 3 1 2]
 ['Manager' 4 1 1]
 ['Country Manager' 5 1 4]
 ['Region Manager' 6 1 2]
 ['Partner' 7 1 1]
 ['Senior Partner' 8 1 1]
 ['C-level' 9 1 1]
 ['CEO' 10 1 2]
 ['Business Analyst' 1 2 3]
 ['Junior Consultant' 2 5 4]
 ['Senior Consultant' 3 3 2]
 ['Manager' 4 6 2]
 ['Country Manager' 5 4 3]
 ['Region Manager' 6 2 1]
 ['Partner' 7 3 3]
 ['Senior Partner' 8 2 4]
 ['C-level' 9 3 1]
 ['CEO' 10 4 3]]


In [27]:
print(y)

0       45000
1       50000
2       60000
3       80000
4      110000
5      150000
6      200000
7      300000
8      500000
9     1000000
10      60000
11      65000
12      70000
13      90000
14     150000
15     180000
16     340000
17     450000
18     600000
19    1500000
Name: Salary, dtype: int64


In [10]:
df.shape

(20, 5)

In [28]:
#Codificamos la columna "Position"
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(),[0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [29]:
print(X)

[[1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 1 2]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3 1 2]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 4 1 1]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 5 1 4]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 6 1 2]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 7 1 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 8 1 1]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 9 1 1]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 10 1 2]
 [1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1 2 3]
 [0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 2 5 4]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 3 3 2]
 [0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 4 6 2]
 [0.0 0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 5 4 3]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 6 2 1]
 [0.0 0.0 0.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 7 3 3]
 [0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 1.0 8 2 4]
 [0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 9 3 1]
 [0.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 10 4 3]]


In [35]:
y =np.array(y)
type(y)

numpy.ndarray

## splitting the Dataset into the Training set and Test set

In [36]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)


## Training the multiple Linear Regression model on the Training set

In [37]:
# Se usa la misma librería como la de Simple Linear Regression, esta clase identificará que hay múltples features.
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set result

In [38]:
# Se crea las predicciones basado en los features del test set.
y_pred = regressor.predict(X_test)
#Visualiza cada ganancia prevista con dos decimales después del punto.
np.set_printoptions(precision=2)
# se usa la función concatenar los dos vectores horizontal o vertical. En nuestro caso lo haremos vertical.
#Los dos vectores deben de tener el mismo tamaño
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),axis=1))

[[ 552684.78  600000.  ]
 [ -74005.85   50000.  ]
 [1058859.65 1500000.  ]
 [ 537655.54  500000.  ]]
